global variables checking for server-side render
sorry, my previous PR didn't fix it
document and window also require checking

Unable to read file: /Users/egorshar/Desktop/project-preact/src/node_modules/hotkeys-js/dist/hotkeys.min.js

ReferenceError: document is not defined
method: null
at: /Users/egorshar/Desktop/project-preact/src/node_modules/hotkeys-js/dist/hotkeys.min.js:2:2977

This is most likely caused by using DOM or Web APIs.
Pre-render runs in node and has no access to globals available in browsers.